# Generated by Django 4.1.1 on 2022-10-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='slug',
            field=models.SlugField(default='stuff'),
            preserve_default=False,
        ),
    ]
